blogicum/blog/urls.py
from . import views
from django.urls import path

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('category/<slug:category_slug>/', views.category_posts,
         name='category_posts')
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('pages/', include('pages.urls', namespace='pages')),
]

blogicum/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('rules/', views.rules, name='rules'),
]

blogicum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('pages/', include('pages.urls', namespace='pages')),
]

blogicum/blog/views.py
from django.shortcuts import render
from django.http import Http404

posts = [
    {
        'id': 0,
        'location': 'Остров отчаянья',
        'date': '30 сентября 1659 года',
        'category': 'travel',
        'text': '''Наш корабль, застигнутый в открытом море
                страшным штормом, потерпел крушение.
                Весь экипаж, кроме меня, утонул; я же,
                несчастный Робинзон Крузо, был выброшен
                полумёртвым на берег этого проклятого острова,
                который назвал островом Отчаяния.''',
    },
    {
        'id': 1,
        'location': 'Остров отчаянья',
        'date': '1 октября 1659 года',
        'category': 'not-my-day',
        'text': '''Проснувшись поутру, я увидел, что наш корабль сняло
                с мели приливом и пригнало гораздо ближе к берегу.
                Это подало мне надежду, что, когда ветер стихнет,
                мне удастся добраться до корабля и запастись едой и
                другими необходимыми вещами. Я немного приободрился,
                хотя печаль о погибших товарищах не покидала меня.
                Мне всё думалось, что, останься мы на корабле, мы
                непременно спаслись бы. Теперь из его обломков мы могли бы
                построить баркас, на котором и выбрались бы из этого
                гиблого места.''',
    },
    {
        'id': 2,
        'location': 'Остров отчаянья',
        'date': '25 октября 1659 года',
        'category': 'not-my-day',
        'text': '''Всю ночь и весь день шёл дождь и дул сильный
                порывистый ветер. 25 октября.  Корабль за ночь разбило
                в щепки; на том месте, где он стоял, торчат какие-то
                жалкие обломки,  да и те видны только во время отлива.
                Весь этот день я хлопотал  около вещей: укрывал и
                укутывал их, чтобы не испортились от дождя.''',
    },
]

posts_dict = {post['id']: post for post in posts}


def index(request):
    context = {'posts': posts[::-1]}
    return render(request, 'blog/index.html', context)


def post_detail(request, post_id):
    post = posts_dict.get(post_id)
    if post is None:
        raise Http404('Указан неверный id')
    context = {'post': post, }
    return render(request, 'blog/detail.html', context)


def category_posts(request, category_slug):
    return render(request, 'blog/category.html',
                  {'category_slug': category_slug})

blogicum/pages/views.py
from django.shortcuts import render


def about(request):
    templates = 'pages/about.html'
    return render(request, templates)


def rules(request):
    templates = 'pages/rules.html'
    return render(request, templates)

blogicum/templates/blog/category.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Категория</title>
</head>
<body>
<main>
    <div class="container py-5">
        <h1>Публикации в категории - {{ category_slug }}</h1>
    </div>
</main>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blogicum/templates/blog/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Детали поста</title>
</head>
<body>
<main>
    <div class="container py-5">
        <h1>Детали записи</h1>
        <ul>
            <li>Место: {{ post.location }}</li>
            <li>Дата: {{ post.date }}</li>
            <li>Категория: {{ post.category }}</li>
        </ul>
        <p>{{ post.text }}</p>
    </div>
</main>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blogicum/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Лента записей</title>
</head>
<body>
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
            <a class="navbar-brand" href="{% url 'blog:index' %}">
                <img src="{% static 'img/logo.png' %}" width="30" height="30" alt="">
                Блогикум
            </a>
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'blog:index' %}">Лента записей</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:about' %}">О проекте</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:rules' %}">Наши правила</a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<main>
    <div class="container py-5">
        <h1>Лента записей</h1>
        {% for post in posts %}
        <hr>
        <article>
            <ul>
                <li>Место: {{ post.location }}</li>
                <li>Дата: {{ post.date }}</li>
                <li>Категория: <a href="{% url 'blog:category_posts' post.category %}">{{ post.category }}</a></li>
            </ul>
            <p>{{ post.text|truncatewords:10 }}</p>
            <a href="{% url 'blog:post_detail' post.id %}">Читать полный текст</a>
        </article>
        {% endfor %}
    </div>
</main>
<footer class="border-top text-center py-3">
    <p>© Блогикум</p>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blogicum/templates/pages/about.html
<h1>О проекте</h1>
<p>Описание проекта</p>

blogicum/templates/pages/rules.html
<h1>Правила</h1>
<p>Правила использования сайта</p>